### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

In [0]:
arr = np.random.randint(1, 51, 10)
print(f"Media: {np.mean(arr)}")
print(f"STD:   {np.std(arr)}")

Media: 29.5
STD:   13.139634698118513


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)
print(f"Original: {arr}")
arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])
print(f"Raiz: {arr}")

Original: [0.37063154 0.22878544 0.2602463  0.51958835 0.08280917 0.42463577
 0.63118383 0.39591612 0.72176472 0.72094741]
Raiz: [0.60879515 0.47831521 0.51014341 0.51958835 0.28776582 0.65164083
 0.63118383 0.62921866 0.72176472 0.72094741]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3,3,3)
print(f"Original: {matriz}")
print(np.amax(matriz, axis = 1))

Original: [[[0.37067787 0.20624696 0.86866513]
  [0.1850371  0.22267076 0.15911992]
  [0.54875126 0.81312361 0.38058059]]

 [[0.79285906 0.27650894 0.23457619]
  [0.23848627 0.09309719 0.68517916]
  [0.26125704 0.03377529 0.11760382]]

 [[0.67210288 0.63043163 0.8209653 ]
  [0.44827587 0.81050768 0.86825381]
  [0.63208232 0.24427842 0.63244395]]]
[[0.54875126 0.81312361 0.86866513]
 [0.79285906 0.27650894 0.68517916]
 [0.67210288 0.81050768 0.86825381]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5,5)
print(f"Original: {matriz}")
print("="*100)
for row in range(len(matriz)):
  mean_row = np.mean(matriz[row])
  print(f"Mean {row}: {mean_row}")
  for col in range(len(matriz[row])):
    matriz[row][col] = matriz[row][col] - mean_row
    
print(matriz)

Original: [[0.56339286 0.701537   0.03949326 0.33419156 0.53395157]
 [0.43103527 0.14204867 0.80107699 0.08063273 0.35018759]
 [0.90168187 0.17537148 0.6258423  0.52410384 0.98644859]
 [0.43854227 0.57737236 0.51985236 0.08816507 0.48359498]
 [0.2990666  0.13283619 0.22710435 0.24933887 0.32768441]]
Mean 0: 0.4345132477698651
Mean 1: 0.36099625077128883
Mean 2: 0.642689614024654
Mean 3: 0.42150540759802657
Mean 4: 0.24720608412343276
[[ 0.12887961  0.26702375 -0.39501999 -0.10032169  0.09943832]
 [ 0.07003902 -0.21894758  0.44008074 -0.28036352 -0.01080866]
 [ 0.25899226 -0.46731814 -0.01684732 -0.11858577  0.34375897]
 [ 0.01703686  0.15586695  0.09834695 -0.33334034  0.06208957]
 [ 0.05186052 -0.1143699  -0.02010174  0.00213279  0.08047833]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4,4)
print(f"Original: {matriz}")
principal  = np.diagonal(matriz)
secundaria = np.diagonal(np.fliplr(matriz))
print(f"Principal : {principal}")
print(f"Secundatia: {secundaria}")
print(f"Means: {np.mean([principal, secundaria])}")
print(f"Stds:  {np.std([principal, secundaria])}")

Original: [[0.00514698 0.18344057 0.08947358 0.64672627]
 [0.34915043 0.51077346 0.79899705 0.30554476]
 [0.37940227 0.85756733 0.64525661 0.30175727]
 [0.20661208 0.18340192 0.5115028  0.32424104]]
Principal : [0.00514698 0.51077346 0.64525661 0.32424104]
Secundatia: [0.64672627 0.79899705 0.85756733 0.20661208]
Means: 0.4994151021705586
Stds:  0.27880150627458244
